# Generated by Django 5.1.3 on 2024-12-01 05:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Pemesanan',
        ),
        migrations.RenameField(
            model_name='pemesanan',
            old_name='order_kuantitas',
            new_name='pemesanan_kuantitas',
        ),
    ]
