# Generated by Django 5.1.3 on 2024-12-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_order_pemesanan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pemesanan',
            options={'verbose_name': 'Pemesanan', 'verbose_name_plural': 'Staff Pemesanan'},
        ),
        migrations.AlterModelOptions(
            name='produk',
            options={'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
    ]
